name: tfg
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - numpy
  - pandas
  - pytorch==1.12.*
  - fastapi==0.74.*
  - requests==2.27.*
  - sentencepiece==0.1.*
  - transformers
  - uvicorn[standard]==0.17.*
  - codecarbon
  - gunicorn
  - accelerate
  - seaborn
  - matplotlib
  - tabulate
  - scipy