name: tfg
channels:
  - conda-forge
  - pytorch
  - conda-forge/label/cf202106
  - conda-forge/label/cf202107
  - anaconda
dependencies:
  - python=3.10.*
  - numpy
  - pandas
  - torch
  - fastapi==0.74.*
  - requests==2.27.*
  - sentencepiece==0.1.*
  - transformers
  - uvicorn[standard]==0.17.*
  - codecarbon
  - gunicorn
  - accelerate
  - seaborn
  - matplotlib
  - tabulate
  - scipy
  - scikit-learn
  - tensorflow
  - tensorflow-model-optimization
  - datasets