# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tfgdemo2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tfgdemo2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6908ca52952249b29cd1d3bda28e7be0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_12767dabdcca4a0c83e77ed0d3ae40e1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tfgdemo2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6908ca52952249b29cd1d3bda28e7be0 }}/tfgdemo2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tfgdemo2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39594b78c48943019ff84ae509bc5a8d }}
        images: 'tfgdemo2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6908ca52952249b29cd1d3bda28e7be0 }}/tfgdemo2:${{ github.sha }}'