# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tfgdemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tfgdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bcb97ba049734824a9f22eb782ffc644 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_28893dc37c354ee4a46c7abea1d591b5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tfgdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcb97ba049734824a9f22eb782ffc644 }}/demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tfgdemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ace5c250a5174140847bf382854812dc }}
        images: 'tfgdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcb97ba049734824a9f22eb782ffc644 }}/demo:${{ github.sha }}'